FROM docker-remote.artifacts.developer.gov.bc.ca/ubuntu:latest
RUN apt update && apt install openssh-server net-tools sudo -y
RUN useradd -rm -d /home/edgrad_sftp -s /bin/bash -g root -G sudo -u 1000 edgrad_sftp
RUN service ssh start
EXPOSE 22
USER edgrad_sftp
CMD ["/usr/bin/sshd","-D"]