FROM docker-remote.artifacts.developer.gov.bc.ca/ubuntu:18.04
RUN apt-get update && apt-get install openssh-server openssh-client net-tools sudo -y
RUN useradd -rm -d /home/edgrad_sftp -s /bin/bash -G sudo -u 1000 edgrad_sftp
RUN service ssh start
EXPOSE 22
USER edgrad_sftp
CMD ["/usr/sbin/sshd","-D"]