FROM docker-remote.artifacts.developer.gov.bc.ca/ubuntu:latest
RUN apt-get update && apt-get install openssh-server openssh-client net-tools sudo -y
RUN useradd -rm -d /home/edgrad_sftp -s /bin/bash -G sudo -u 1000 edgrad_sftp
RUN service ssh start
EXPOSE 22
USER edgrad_sftp
RUN ssh-keygen -t rsa -m pem -N "" -f ~/.ssh/id_rsa
CMD ["/usr/sbin/sshd","-D"]