name: Create or Update Keycloak Clients

on:
  workflow_dispatch:

jobs:
  create-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create or update clients in Keycloak
        uses: actions/github-script@v7
        env:
          KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
          KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
          KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
          KEYCLOAK_ADMIN_PASS: ${{ secrets.KEYCLOAK_ADMIN_PASS }}
        with:
          script: |
            const fs = require('fs');
            const vm = require('vm');
            const axios = require('axios');

            const scriptCode = fs.readFileSync('./tools/config/clients-and-scopes.js', 'utf8');

            const module = { exports: {} };
            const sandbox = { require, module, console, process, axios };

            vm.createContext(sandbox);
            vm.runInContext(scriptCode, sandbox);

            await module.exports({ github, context, core });
