name: IaC for KC Clients and OC Secrets
run-name: IaC for KC Clients and OC Secrets in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs: 
      environment:
        type: environment

jobs:
  create-or-update-clients:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Create/Update clients in Keycloak
        run: node ./tools/config/clients-and-scopes.js
        env:
          KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
          KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
          KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
          KEYCLOAK_ADMIN_PASS: ${{ secrets.KEYCLOAK_ADMIN_PASS }}

      - name: Create/Update client secrets in OC
        run: node ./tools/openshift/fetch-and-create-secrets.js
        env:
          KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
          KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
          KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
          KEYCLOAK_ADMIN_PASS: ${{ secrets.KEYCLOAK_ADMIN_PASS }}

          OPENSHIFT_SERVER: ${{ vars.OPENSHIFT_SERVER }}
          OPENSHIFT_NAMESPACE: ${{ vars.GRAD_NAMESPACE }}-${{ github.event.inputs.environment }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
